USE [master]
GO

/****** Object:  Database [Bet]    Script Date: 27/03/2022 18:25:33 ******/
CREATE DATABASE [Bet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bet', FILENAME = N'/var/opt/mssql/data/Bet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bet_log', FILENAME = N'/var/opt/mssql/data/Bet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO


ALTER DATABASE [Bet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bet] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bet] SET RECOVERY FULL 
GO

ALTER DATABASE [Bet] SET  MULTI_USER 
GO

ALTER DATABASE [Bet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Bet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Bet] SET  READ_WRITE 
GO


USE [Bet]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Account](
	[UserId] [nvarchar](50) NOT NULL,
	[Balance] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Bet]
GO
USE [Bet]
GO

/****** Object:  Table [dbo].[Betslip]    Script Date: 29/03/2022 20:48:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Betslip](
	[Id] [varchar](32) NOT NULL,
	[Channel] [varchar](10) NOT NULL,
	[Timestamp] [datetime2](7) NOT NULL,
	[UserId] [varchar](32) NOT NULL,
	[Game] [varchar](32) NOT NULL,
	[Market] [varchar](32) NOT NULL,
	[Outcome] [varchar](32) NOT NULL,
	[RequestedOdd] [decimal](18, 0) NOT NULL,
	[ExecutedOdd] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_Betslip] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO




